import { describe, expect, it } from 'vitest';
import { UndirectedGraph } from '../src/graph.js';
import { EsuTree } from '../src/esu.js';
import { Shape } from '../src/shape.js';
import { SAMPLES } from './samples.js';
import golden from './java-golden.json';

/**
 * The port has to agree with the desktop app, not merely be self-consistent.
 *
 * java-golden.json is generated by the Java implementation: for each sample
 * graph and size, which node every single step builds, how many subgraphs
 * are found, and exactly which ones.
 *
 * The trace is the point. Totals alone do not pin the traversal: reversing
 * the order candidates are taken in yields the same number of steps and the
 * same answers by a different route, and an earlier version of this test
 * passed with exactly that mutation in place. The visualizer shows the search
 * step by step, so the route is observable behaviour.
 */
interface Case {
  file: string;
  k: number;
  steps: number;
  count: number;
  trace: string[];
  shapes: Array<{ name: string; edges: number; count: number; drawn: string }>;
  subgraphs: string[];
}

describe('agreement with the Java implementation', () => {
  for (const expected of golden as Case[]) {
    const { file, k } = expected;

    it(`matches Java on ${file} at k=${k}`, () => {
      const graph = UndirectedGraph.parse(SAMPLES[file]!);
      const tree = new EsuTree(graph, k);

      const trace: string[] = [];
      while (tree.step()) {
        const last = tree.log[tree.log.length - 1];
        trace.push((last?.caller ?? '?').replace(/ /g, ''));
        tree.clearLog();
      }

      const subgraphs = tree
        .subgraphs()
        .map((vertices) => `[${[...vertices].sort((a, b) => a - b).join(',')}]`)
        .sort();

      expect({
        steps: trace.length,
        count: subgraphs.length,
        trace,
        subgraphs,
      }).toEqual({
        steps: expected.steps,
        count: expected.count,
        trace: expected.trace,
        subgraphs: expected.subgraphs,
      });
    });

    it(`groups ${file} at k=${k} into the same shapes as Java`, () => {
      const graph = UndirectedGraph.parse(SAMPLES[file]!);
      const tree = new EsuTree(graph, k);
      while (tree.step()) tree.clearLog();

      // Names, counts, ordering, and the edges each shape draws. The drawing
      // is included because it was wrong in Java in a way nothing else saw:
      // every pair read the same bit, so shapes drew identically.
      const shapes = Shape.classify(graph, tree.subgraphs()).map((entry) => ({
        name: entry.shape.name(),
        edges: entry.shape.edges,
        count: entry.count,
        drawn: drawingOf(entry.shape),
      }));

      expect(shapes).toEqual(expected.shapes);
    });
  }
});

/** The edges a shape draws, in the form the fixture records. */
function drawingOf(shape: Shape): string {
  const pairs: string[] = [];
  for (let from = 0; from < shape.size; from++) {
    for (let to = from + 1; to < shape.size; to++) {
      if (shape.joins(from, to)) pairs.push(`${from}-${to}`);
    }
  }
  return pairs.join(',');
}
