/**
 * The ESU algorithm, ported from `EsuNode.java` and `EsuTree.java`.
 *
 * A faithful port, not a tidier reimplementation: the visualizer shows the
 * search one step at a time, so the *order* the tree is built in is part of
 * the observable behaviour, not an implementation detail. The tests check
 * step counts against fixtures generated by the Java version for that reason.
 */
import { UndirectedGraph } from './graph.js';

/** One line of the algorithm's commentary on itself. */
export interface StepEntry {
  /** The subgraph this entry is about, e.g. `"{0, 2}"`. */
  readonly caller: string;
  /** Already-rendered text, with node placeholders resolved. */
  readonly text: string;
}

/** A smallest-first queue. The Java uses a PriorityQueue of Integer, and
 *  which vertex is taken next decides the shape of the tree. */
class MinQueue {
  private items: number[] = [];

  add(value: number): void {
    this.items.push(value);
    this.items.sort((a, b) => a - b);
  }

  poll(): number | null {
    return this.items.length === 0 ? null : this.items.shift()!;
  }

  values(): number[] {
    return [...this.items];
  }

  get size(): number {
    return this.items.length;
  }
}

export class EsuNode {
  readonly level: number;
  /** The vertex this node added. Null only for the root. */
  readonly myStep: number | null;
  /** The vertex the branch began at, which the labelling rule compares to. */
  readonly firstStep: number | null;
  readonly parent: EsuNode | null;
  readonly children: EsuNode[] = [];

  /** Vertices this node may still add. */
  readonly possibleSteps = new MinQueue();
  /** Vertices already seen from this node's subgraph. Null for the root. */
  readonly subgraphNeighbors: number[] | null;

  private constructor(
    private readonly tree: EsuTree,
    private readonly graph: UndirectedGraph,
    parent: EsuNode | null,
    myStep: number | null,
  ) {
    this.parent = parent;
    this.myStep = myStep;

    if (parent === null) {
      this.level = 0;
      this.firstStep = null;
      this.subgraphNeighbors = null;
      for (const vertex of graph.connectedVertices()) this.possibleSteps.add(vertex);
    } else {
      this.level = parent.level + 1;
      this.firstStep = this.level === 1 ? myStep : parent.firstStep;
      this.subgraphNeighbors = [];
    }
  }

  static root(tree: EsuTree, graph: UndirectedGraph): EsuNode {
    return new EsuNode(tree, graph, null, null);
  }

  /** The vertices of this node's subgraph, in the order they were added. */
  subgraph(): number[] {
    const out: number[] = [];
    for (let node: EsuNode | null = this; node?.myStep !== null && node !== null; node = node.parent) {
      out.unshift(node.myStep);
    }
    return out;
  }

  /** `"{0, 2}"` — the form the Java logs use, so the text matches. */
  subgraphLabel(): string {
    return `{${this.subgraph().join(', ')}}`;
  }

  possibleStepsLabel(): string {
    return `(${this.possibleSteps.values().join(', ')})`;
  }

  neighborsLabel(): string {
    return `[${(this.subgraphNeighbors ?? []).join(', ')}]`;
  }

  /**
   * Take one step of the search, depth first.
   *
   * Named to match EsuNode.step in the Java, which is the reference: the two
   * implementations are checked against each other, and reading them side by
   * side is easier when the same thing has the same name.
   *
   * @returns true if this node or a descendant took a step
   */
  step(): boolean {
    if (this.level === this.tree.maxHeight) return false;

    for (const child of this.children) {
      if (child.step()) return true;
    }

    const next = this.possibleSteps.poll();
    if (next === null) return false;

    const child = new EsuNode(this.tree, this.graph, this, next);
    this.tree.log.push({ caller: this.subgraphLabel(), text: 'Creating new node.' });
    this.children.push(child);
    child.setLists();
    this.tree.log.push({
      caller: child.subgraphLabel(),
      text: `Finished making node ${child.subgraphLabel()}.`,
    });
    return true;
  }

  /**
   * Work out what this new node may go on to add: inherit the parent's
   * candidates, then consider the neighbors of the vertex just added.
   */
  private setLists(): void {
    const label = this.subgraphLabel();

    if (this.level >= this.tree.maxHeight) {
      this.tree.leaves.push(this);
      this.tree.log.push({
        caller: label,
        text: `Created a unique subgraph ${label}.`,
      });
      return;
    }

    const parent = this.parent!;
    if (parent.myStep !== null) {
      this.tree.log.push({
        caller: label,
        text: `Create node ${label}, copy ${parent.subgraphLabel()}'s possible steps `
          + `${parent.possibleStepsLabel()} into ${label}'s possible steps () `
          + `and subgraph neighbors [].`,
      });
      for (const candidate of parent.possibleSteps.values()) {
        this.possibleSteps.add(candidate);
        this.subgraphNeighbors!.push(candidate);
      }
    }

    const neighbors = this.graph.neighbors(this.myStep!);
    this.tree.log.push({
      caller: label,
      text: `Getting ${this.myStep}'s neighbors: { ${neighbors.join(', ')} }.`,
    });

    for (const neighbor of neighbors) {
      // The labelling rule: a branch may only grow into vertices numbered
      // above the one it started from. This is what makes every subgraph
      // turn up exactly once.
      if (neighbor <= this.firstStep!) {
        this.tree.log.push({
          caller: label,
          text: `${neighbor} is less than or equal to this branch's first step `
            + `(${this.firstStep}). Validation denied.`,
        });
      } else if (this.checkAncestors(neighbor, label)) {
        this.tree.log.push({
          caller: label,
          text: `${neighbor} added to ${label}'s lists.`,
        });
        this.possibleSteps.add(neighbor);
        this.subgraphNeighbors!.push(neighbor);
      }
    }
  }

  /**
   * Walk up the branch rejecting a vertex already accounted for, so the same
   * subgraph is not reached by two different routes.
   *
   * @param vertex the candidate being validated
   * @param caller label of the node the log entries are about
   */
  private checkAncestors(vertex: number, caller: string): boolean {
    if (this.myStep === null) {
      this.tree.log.push({ caller, text: `Validation approved for ${vertex}.` });
      return true;
    }
    if (vertex === this.myStep || this.subgraphNeighbors!.includes(vertex)) {
      this.tree.log.push({
        caller,
        text: `${vertex} was found in ${this.subgraphLabel()}'s data. Validation denied.`,
      });
      return false;
    }
    this.tree.log.push({
      caller,
      text: `${vertex} was not found in ${this.subgraphLabel()}'s data. Validation continues.`,
    });
    return this.parent!.checkAncestors(vertex, caller);
  }
}

export class EsuTree {
  readonly root: EsuNode;
  readonly leaves: EsuNode[] = [];
  log: StepEntry[] = [];

  constructor(
    graph: UndirectedGraph,
    /** The k in "connected subgraphs of size k". */
    readonly maxHeight: number,
  ) {
    this.root = EsuNode.root(this, graph);
  }

  /** Take one step. Returns false once the search is exhausted. */
  step(): boolean {
    return this.root.step();
  }

  clearLog(): void {
    this.log = [];
  }

  /** The subgraphs found so far, each as its vertices in insertion order. */
  subgraphs(): number[][] {
    return this.leaves.map((leaf) => leaf.subgraph());
  }

  /** Nodes by depth, index 0 being the root alone. */
  nodesByLevel(): EsuNode[][] {
    const levels: EsuNode[][] = Array.from({ length: this.maxHeight + 1 }, () => []);
    const visit = (node: EsuNode): void => {
      levels[node.level]!.push(node);
      for (const child of node.children) visit(child);
    };
    visit(this.root);
    return levels;
  }
}
